# Generated by Django 4.2.11 on 2024-05-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('jenis', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('harga', models.IntegerField()),
            ],
            options={
                'db_table': 'paket',
            },
        ),
    ]
