# Generated by Django 4.2.11 on 2024-05-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_akun'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='akun',
            table='akun',
        ),
    ]
