# Generated by Django 4.2.11 on 2024-05-17 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_akun_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konten',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('tanggal_rilis', models.DateField()),
                ('tahun', models.IntegerField()),
                ('durasi', models.IntegerField()),
            ],
            options={
                'db_table': 'konten',
            },
        ),
        migrations.CreateModel(
            name='PemilikHakCipta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_royalti', models.IntegerField()),
            ],
            options={
                'db_table': 'pemilik_hak_cipta',
            },
        ),
    ]
