# Generated by Django 4.2.11 on 2024-05-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_konten_pemilikhakcipta'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
