# Generated by Django 4.2.11 on 2024-05-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_akun_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akun',
            name='last_login',
        ),
    ]
