# Generated by Django 4.2.11 on 2024-05-17 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_akun_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('akun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.akun')),
            ],
            options={
                'db_table': 'premium',
            },
        ),
    ]
