# Generated by Django 4.2.11 on 2024-05-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_playlist_premium'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
