# Generated by Django 4.2.11 on 2024-05-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_playlist'),
        ('main', '0010_playlist'),
    ]

    operations = [
    ]
