# Generated by Django 4.2.11 on 2024-05-17 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_0009_playlist_0010_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPremium',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.akun')),
            ],
            options={
                'db_table': 'non_premium',
            },
        ),
        migrations.RemoveField(
            model_name='premium',
            name='akun',
        ),
        migrations.AlterField(
            model_name='premium',
            name='email',
            field=models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.akun'),
        ),
    ]
