# Generated by Django 4.2.11 on 2024-05-17 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_nonpremium_remove_premium_akun_alter_premium_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcaster',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.akun')),
            ],
            options={
                'db_table': 'podcaster',
            },
        ),
    ]
