# Generated by Django 4.2.11 on 2024-05-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_genre_id_alter_genre_id_konten'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
