# Generated by Django 4.2.11 on 2024-05-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_konten', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.konten')),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genre',
                'unique_together': {('id_konten', 'genre')},
            },
        ),
    ]
