# Generated by Django 4.2.11 on 2024-05-17 07:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='id_konten',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.konten'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_dimulai', models.DateTimeField()),
                ('timestamp_berakhir', models.DateTimeField()),
                ('metode_bayar', models.CharField(max_length=50)),
                ('nominal', models.IntegerField()),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.akun')),
                ('jenis_paket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.paket')),
            ],
            options={
                'db_table': 'transaction',
                'unique_together': {('id', 'jenis_paket', 'email')},
            },
        ),
    ]
